name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Run AI Review
        uses: hozaifaO/AY-I-WILL-CODE-REVIEW@master
        with:
          openai_key: ${{ secrets.OPENAI_KEY }}
          model: ${{ inputs.model }}     # if you needed to override
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

