name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AI Review
        uses: hozaifaO/AY-I-WILL-CODE-REVIEW@master
        with:
          azure-endpoint: ${{ secrets.AZURE_ENDPOINT }}
          azure-api-key:  ${{ secrets.AZURE_API_KEY }}
          azure-model:    DeepSeek-V3-0324
        env:
          GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER:         ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
