name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3
      - name: Run AI Review
        uses: hozaifaO/AY-I-WILL-CODE-REVIEW@main
        with:
          openai-key: ${{ secrets.OPENAI_KEY }}
